### ISSUE TITLE
More consistent indentation for predicate/objects attached to the same subject

### ISSUE THREAD

**Issue by vemonet** [IoannisNezis/Qlue-ls#3]
Hi, currently the formatting of SPARQL queries aligns predicates/objects based on the length of the subject, e.g.:

```sparql
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX up:   <http://purl.uniprot.org/core/>
SELECT DISTINCT ?diseaseLabel ?humanProtein ?hgncSymbol ?orthologRatProtein ?orthologRatGene WHERE {
  ?humanProtein a up:Protein ;
                up:organism/up:scientificName 'Homo sapiens' ;
                up:annotation ?diseaseAnnotation ;
                rdfs:seeAlso ?hgnc .
  ?hgnc up:database <http://purl.uniprot.org/database/HGNC> ;
        rdfs:comment ?hgncSymbol .
  ?diseaseAnnotation a up:Disease_Annotation ;
                     up:disease ?disease .
  ?disease a up:Disease ;
           skos:prefLabel ?diseaseLabel .
}
```

Would it be possible to consider just going to the line and adding a regular indent? e.g. 

```sparql
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX up: <http://purl.uniprot.org/core/>
SELECT DISTINCT ?diseaseLabel ?humanProtein ?hgncSymbol ?orthologRatProtein ?orthologRatGene
WHERE {
  ?humanProtein a up:Protein ;
    up:organism/up:scientificName 'Homo sapiens' ;
    up:annotation ?diseaseAnnotation ;
    rdfs:seeAlso ?hgnc .
  ?hgnc up:database <http://purl.uniprot.org/database/HGNC> ;
    rdfs:comment ?hgncSymbol .
  ?diseaseAnnotation a up:Disease_Annotation ;
    up:disease ?disease .
  ?disease a up:Disease ;
    skos:prefLabel ?diseaseLabel.
}
```

I know it might seems like "a personal preference" but I think their are a few objective arguments for going for the regular indent approach:

* More consistent, predictable, and easier to read: it's always the same predictable length, making it easier for the readers eyes, they know exactly where to go after a new line, no need to search for the next predicate. 
* You don't end up with different weirdly shaped queries (cf. the examples given above, which one is easier to read?) and uneven indent length
* It is the solution that have been adopted by every popular opiniated code formatters that I know of, such as `black`/`ruff-format` in python, `prettier`/`rome`/`biome` in javascript, and rustfmt. Maybe there is a reason for that :)

**Comment by IoannisNezis** [comment]
Hey @vemonet,
fair point.
To be perfectly honest with you, i mainly implemented this to test tree-sitter queries and thought it was "cool".

One of the next things i would like to do is create a user-configuration.
I'll add "align predicates" as a configurable option. Then we can argue about what the default should be :)
Are there already other things about the formatter that you would like to have customizable?

**Comment by vemonet** [comment]
Yes it is quite cool indeed :) I'll make my list to Santa Claus then!

I don't know if it is worth to go to configuration but `WHERE {` should go to a newline imo

For configuration I could see these maybe:
* Number of spaces per indent (but I guess this is some kind of default from the IDE)
* Adding an empty newline after the prefixes declaration (gives more air, but sometime you want to keep it tight)
* Always adding the `WHERE` when it is not there
* Automatically putting keywords as capital letters (default to yes, but some weird people might want to keep some keywords lowercase... Some might even want you to add the option to put all of them lowercase...)
* Aligning or not the URIs from the prefixes namespaces (currently you align them, some people might just want 1 space separation from the prefix)
* Automatically converting URIs to prefixes if prefixes are available for these URIs (we recently made a [curies.rs](https://biopragmatics.github.io/curies.rs/) crate that compiles to wasm in case you need)
* If it is possible: automatically concatenate all predicates that are under the same subject, and all objects that are under the same predicate. So these patterns:
  
  ```sparql
  ?hgnc up:database <http://purl.uniprot.org/database/HGNC> .
  ?hgnc up:database <http://purl.uniprot.org/database/OMA> .
  ?hgnc rdfs:comment ?hgncSymbol .
  ```
  
  Would become:
  
  ```sparql
  ?hgnc up:database <http://purl.uniprot.org/database/HGNC>, <http://purl.uniprot.org/database/OMA> ;
     rdfs:comment ?hgncSymbol .
  ```
  
  That would be so good! (should not break the boundaries of subqueries obviously)



fyi I tried `pipx install fichu` (cool name!) and currently getting:

```bash
fichu format ./query.rq
thread 'main' panicked at src/main.rs:39:6:
called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)
```

**Comment by IoannisNezis** [comment]
Nice, thanks for the input!

Some of the suggestions, like the conversion of URIs (thanks for the CURIEs hint btw, looks awesome), sound more like [Code Actions](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_codeAction) to me.

I think i want formatting only to reorder the tokens and not add or delete anything (but whitespace) and put more complex refactor operations into separate code actions.

> fyi I tried pipx install fichu (cool name!) and currently getting:
>```
> fichu format ./query.rq
> thread 'main' panicked at src/main.rs:39:6:
> called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)
> ```

The bug should have been fixed in `0.1.7`.

**Comment by IoannisNezis** [comment]
Closing this as most of the whishlist is implemented now.
The remaining ones are documented in my internal notes and will eventually be added.
